### ISSUE TITLE
fastQValidator subprocess call, OSError: [Errno 2] No such file or directory 

### ISSUE THREAD

**Issue by jowong4** [CPTR-ReSeqTB/UVP#2]
/usr/bin/uvp/scripts/UVP -q  /loc/id_1.fastq.gz -r /loc/ref/genomic.fna -n test
Traceback (most recent call last):
  File "/usr/bin/uvp/scripts/UVP", line 97, in <module>
    args.verbose, ' '.join(sys.argv))
  File "/usr/bin/uvp/scripts/UVP.py", line 58, in __init__
    with open("/uvp/scripts/config.yml", 'r') as ymlfile:
IOError: [Errno 2] No such file or directory: '/uvp/scripts/config.yml'

I've been getting this error and I've tried adding the path to the environment before running but it still doesnt work

**Comment by jowong4** [comment]
I also tried running the newest commit which solved that issue but instead i got another problem 
Traceback (most recent call last):
  File "/usr/bin/UVP/scripts/UVP", line 98, in <module>
    s.runVali()
  File "/usr/bin/UVP/scripts/UVP.py", line 144, in runVali
    self.__CallCommand(['fastQValidator', valiOut + '/result.out'], [self.__fastqval,'--file', self.input])
  File "/usr/bin/UVP/scripts/UVP.py", line 110, in __CallCommand
    p = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Ive installed fastQvalidator and have the executable in my path but it still produces the error

**Comment by mezewudo** [comment]
You will want to look at the README document, you should edit file paths to fit your local machine installation.
